  function loadBio(){
    $('#mainblock').text("A bit about me");
  }

  function loadWork(){

//$('#mainblock').text("Work work work");
	document.getElementById("mainblock").setAttribute("style","height:100%;, background-color:#FEFEFE");
	document.getElementById("mainblock").setAttribute("style","height:100%;, background-color:#FEFEFE");
	$('#mainblock').html('<img src="media/lines.png" style="width:30%;height:30%;"><div class="container">	<div class="panel-group" id="accordion"><div class="panel panel-default"><div class="panel-heading" style="background-color:#A1BFED;width:100%;"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Experience</a></h4></div><div id="collapse1" class="panel-collapse collapse in">  <div class="panel-body"><table style="border-spacing:15px;border-collapse:separate;width:50%;"><tr><td style="padding-left:10px;">Last Stop:<br><br>Tampere<br><span class="description">Software Development Engineer in Test – Summer trainee</span></td></tr><tr><td style="padding-left:10px;">Previous stops:<br><br>San Diego<br><span class="description animated infinite bounce">Software Test Engineer (Qualcomm - MDM)</span><br><br>Monterrey<br><span class="description">Sr. Test Engineer (Texas Instruments - OMAP)</span><br><span class="description">Software Engineer (Texas Instruments - OMAP)</span><br><br>Mexico City<br><span class="description animated infinite bounce">Mobile Applications Developer</span></td></tr></table></div></div></div><div class="panel panel-default"><div class="panel-heading" style="background-color:#A1EDD2;width:100%;"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Education</a></h4></div>  <div id="collapse1" class="panel-collapse collapse in">  <div class="panel-body"><table style="border-spacing:15px;border-collapse:separate;width:50%;"><tr><td style="padding-left:10px;">Last stop:<br><br>MSc. in Information Technology<br><span class="description">Focus in User Experience<br>Tampere University of Technology</span></td></tr><tr><td style="padding-left:10px;">Previous stops:<br><br>NYC Disrupt Design Fellowship<br><span class="description">Un-school of Disruptive Design</span></td></tr><tr><td style="padding-left:10px;">Open Source Project: Design Open<br><span class="description">Open Academy, sponsored by Facebook</span></td></tr><tr><td style="padding-left:10px;">BSc. in Electronics &amp; Communications Engineering<br><span class="description">ITESM Campus Monterrey<br>Honors Degree &amp; Student Leadership Diploma</span></td></tr></table></div></div></div></div></div>');
/*	$('#mainblock').html('<h2>Expertise</h2><p></p><div class="subway-map" data-columns="12" data-rows="10" data-cellSize="40" data-legendId="legend" data-textClass="text" data-gridNumbers="false" data-grid="false" data-lineWidth="8"><ul data-color="#ff4db2" data-label="Work Experience"><li data-coords="6,7" >Mexico City</li><li data-coords="5,6" data-dir="W" data-marker="interchange">Monterrey</li><li data-coords="4,5" data-dir="N"></li><li data-coords="3,5" data-dir="W"></li><li data-coords="2,5">San Diego</li><li data-coords="3,4" data-dir="N"></li><li data-coords="8,4"></li><li data-coords="9,3" data-dir="E"></li><li data-coords="10,2"></li><li data-coords="11,2" data-dir="W" data-marker="interchange">Tampere</li></ul><ul data-color="#A1EDD2" data-label="Education" data-shiftCoords="0,-0.5" ><li data-coords="5,6"></li><li data-coords="9,6"></li><li data-coords="10,5" data-dir="E"></li><li data-coords="10,3" data-dir="N"></li><li data-coords="11,2" data-dir="N"></li><li data-coords="11,1" data-dir="N"></li><li data-coords="10,0" data-dir="N"></li><li data-coords="5,0"></li><li data-coords="4,1" data-dir="W"></li><li data-coords="3,2" data-dir="S"></li><li data-coords="2,3" data-dir="W">San Francisco</li><li data-coords="8,3">New York</li></ul></div><p style="height:480;"><table style="border-spacing:15px;border-collapse:separate;width:50%; margin-left:50%;"><tr style="background-color:#A1BFED;width:25%;"><td style="padding-left:10px;">Experience</td></tr><tr><td style="padding-left:10px;">Last Stop:<br><br>Tampere<br><span class="description">Software Development Engineer in Test – Summer trainee</span></td></tr><tr><td style="padding-left:10px;">Previous stops:<br><br>San Diego<br><span class="description animated infinite bounce">Software Test Engineer (Qualcomm - MDM)</span><br><br>Monterrey<br><span class="description">Sr. Test Engineer (Texas Instruments - OMAP)</span><br><span class="description">Software Engineer (Texas Instruments - OMAP)</span><br><br>Mexico City<br><span class="description animated infinite bounce">Mobile Applications Developer</span></td></tr><tr style="background-color:#A1EDD2;width:25%;"><td style="padding-left:10px;">Education</td></tr><tr><td style="padding-left:10px;">Last stop:<br><br>MSc. in Information Technology<br><span class="description">Focus in User Experience<br>Tampere University of Technology</span></td></tr><tr><td style="padding-left:10px;">Previous stops:<br><br>NYC Disrupt Design Fellowship<br><span class="description">Un-school of Disruptive Design</span></td></tr><tr><td style="padding-left:10px;">Open Source Project: Design Open<br><span class="description">Open Academy, sponsored by Facebook</span></td></tr><tr><td style="padding-left:10px;">BSc. in Electronics &amp; Communications Engineering<br><span class="description">ITESM Campus Monterrey<br>Honors Degree &amp; Student Leadership Diploma</span></td></tr></table>');
	 $(".subway-map").subwayMap({ debug: true });
	 */
  }

  function loadProjects(){
    $('#mainblock').text("Presentations");
	
	
  }

  function loadResearch(){
   $('#mainblock').text("Papers and all");
   $('#mainblock').html('<h2>Papers</h2><table style="border-spacing:15px;border-collapse:separate; width:100%;"><tr><td style="width:10%;vertical-align: middle;"><img src="media/icons/Shape-Star2-48.png" style="width:48px; height:48px;margin-left:auto;margin-right:auto;display: block;"><br><br></td>	<td style="font-size:20px;width:90%;"><a href="https://www.researchgate.net/publication/302461114_Burning_up_the_points_An_experimental_research_on_gamification_in_an_Agile_working_environment">Burning up the points: An experimental research on gamification in an Agile working environment</a><br><span class="authors">by Paulina Durán &amp; Samu Lappalainen</span><br><br></td></tr><tr><td style="width:10%;vertical-align: middle;"><img src="media/icons/Mobile-Phone-Music-48.png" style="width:48px; height:48px;margin-left:auto;margin-right:auto;display: block;"></td><td style="font-size:20px;width:90%"><a href="https://www.researchgate.net/publication/303566435_Shumei_a_musical_way_to_change_your_mood_Internet_of_Things_Media_Services_application">Shumei, a musical way to change your mood: Internet of Things &amp; Media Services application</a><br><span class="authors">by Stephanie Arévalo, Paulina Durán &amp; Peng Yao</span></td></tr></table><br><br><h2>Visualizations</h2><table style="border-spacing:15px;border-collapse:separate;width:100%;"><tr><td style="background-color:#A1BFED;width:25%;"><img src="media/infographics/oss1st.png" class="box-img"></td><td style="background-color:#A1BFED;width:25%;"><img src="media/infographics/ossux.png" class="box-img"></td><td style="background-color:#A1BFED;width:25%;"><img src="media/infographics/ecommerce.png" class="box-img"></td><td style="background-color:#A1BFED;width:25%;"><img src="media/infographics/gamification.png" class="box-img"></td></tr><tr><td style="width:25%;">Designers, Developers & Open Source: Research stage.<br><span class="authors">This infographic intended to show how the screening process for topics of interest was performed prior to the study.</span></td><td style="width:25%;">Designers, Developers & Open Source<br><span class="authors">Infographic for the Open Academy project. Open Academy was a Facebook initiative to promote the participation of students in Open Source Projects. Open Design Foundation (formerly known as Design Open) is a project that intends to bring designers as collaborators for open source projects.</span></td><td style="width:25%;">E-Commerce &amp; Social Media <span class="authors">Infographic for the research paper "How Large U.S. Companies Can Use Twitter and Other Social Media to Gain Business Value" by Culnan et al. (2010)</span></td><td style="width:25%;">Gamification &amp; Motivation<br><span class="authors">Visual summary for the paper "Studying gamification: The effect of Rewards and Incentives on Motivation" by Richter, G., Raban, D.R., & Rafaeli, S.</span></td></tr></table>');
  }